### ISSUE TITLE
Mismatching title ID from json files to Store infos

### ISSUE THREAD

**Issue by flok** [sirzechs753/PlayStationDiscord-Games#10]
I'm currently building out the database before i make a PR and found some mismatching of the title ids for some games.

For example Bugsnax with PPSA01502_00 and in store with PPSA01503_00. Are these titleIDs wrong or am i missing something?

I currently have the titleIds of 5005 games from the store api. If we solve this we could adapt the source to use multiple applications and support all 5005 games

**Comment by sirzechs753** [comment]
Are you planning on creating the apps from scratch or modify the original PlayStationDiscord by Tustin?.

Actually I have an idea to improve this kind of program to be able to self update the supported games as more players play games while using the apps since new games keep being released day after day,
But I've been studying Tustin's original repo and still kinda confused of how the code works lol.

**Comment by flok** [comment]
Yeah, the general app is already published, currently working on the games repo to push the game. After that i will probably work on multiple application ids

**Comment by flok** [comment]
Little update:

Games Repo is located at: https://github.com/flok/PlayStationDiscordRPC_Games 
It supports easier adding of new games to the discord application by only adding 2 lines in a yaml file.

https://github.com/flok/PlayStationDiscordRPC will soon get the WebView login like the original tool for easier usage
